#set page(
  paper: "a4",
  margin: (x: 2cm, y: 2.5cm),
  numbering: "1"
)
#set text(font: "Noto Sans CJK JP", lang: "ja", size: 10pt)

// --- ヘッダー ---
#align(center)[
  #text(16pt, weight: "bold")[ {{ title }} ]
  #v(0.5em)
  #text(11pt, style: "italic")[ {{ case_no }} ]
  #h(1fr)
  #text(10pt)[ 判決日: {{ date }} ]
]

#line(length: 100%, stroke: 0.5pt)
#v(1em)

// --- 要約 ---
#block(fill: luma(245), inset: 1em, radius: 5pt, width: 100%)[
  *【要約】* \
  {{ summary }}
]

#v(1em)

// --- 判決結果バッジ ---
*結論:* #box(inset: 5pt, radius: 3pt, fill: black, outset: 0pt)[#text(fill: white, weight: "bold")[ {{ result }} ]]

#v(0.5em)
*Keywords:* {% for kw in keywords %}
  #box(inset: (x: 4pt, y: 2pt), radius: 2pt, fill: luma(230))[#text(size: 9pt)[{{ kw }}]]
{% endfor %}

#v(2em)

// --- 構成要件対比表 (Claim Chart) ---
#heading(level: 2)[構成要件対比表]

#table(
  columns: (30%, 30%, 40%),
  inset: 10pt,
  stroke: 0.5pt + luma(200),
  fill: (_, row) => if calc.odd(row) { luma(250) } else { white },
  align: (col, row) => if row == 0 { center } else { left },

  // Header
  table.header(
    [*構成要件*], [*被告製品の構成*], [*裁判所の判断*]
  ),

  // Loop through Rust data
  {% for row in claim_chart %}
    [ {{ row.requirement }} ],
    [ {{ row.defendant }} ],
    [
      {% if row.is_satisfied %}
        #box(fill: rgb("e6f4ea"), inset: 6pt, radius: 4pt)[
          #text(fill: rgb("137333"), weight: "bold")[✔ 充足 / 一致]
        ]
      {% else %}
        #box(fill: rgb("fce8e6"), inset: 6pt, radius: 4pt)[
          #text(fill: rgb("c5221f"), weight: "bold")[✘ 非充足 / 相違]
        ]
      {% endif %}
      #v(0.5em)
      #text(size: 9pt)[ {{ row.judgment }} ]
    ],
  {% endfor %}
)

#v(2fr)
#align(center + bottom)[
  #text(size: 8pt, fill: luma(150))[Generated by Rust Legal Engine]
]
